### ISSUE TITLE
boxplots if sample name ends with .1 

### ISSUE THREAD

**Issue by iljavh** [UMCUGenetics/DIMS#13]
If the sample names in the input .txt file have no .1 at the end, there are no boxplots generated in the excel output file. Should be fixed or noted in the documentation. (Don't know why this is a necessary name ending, maybe it has some logistic value...)

**Comment by FiniDG-HAN** [comment]
Does this also apply for non Z-score samples?
Because this issue will be fixed in version 2.1.0 as seen in commit e8a25d5c01223614c87db68068b5d28d62d14ba6
[commit](https://github.com/UMCUGenetics/DIMS/commit/e8a25d5c01223614c87db68068b5d28d62d14ba6)
