### ISSUE TITLE
TIMEOUT ERROR bij stap 6 en 11

### ISSUE THREAD

**Issue by FiniDG-HAN** [UMCUGenetics/DIMS#19]
Vaak een TIMEOUT ERROR bij stap 11 en 6. hij heeft te weinig tijd.
ipv de tijd steeds aan te passen (zodat de productionversie eigenlijk niet meer geldig is, vanwege een nieuwe commit) kan er ook iets meer flexibels gebouwen worden, zodat de tijd aangepast kan worden door de gebruiker.

Nienke:
Je kan de tijd configureerbaar maken
Dat je niet code hoeft te veranderen maar een config file
Zoals settings.config
Dan blijft de code vast staan

**Comment by poofcakes** [comment]
Time is now configurable as per commit: https://github.com/UMCUGenetics/DIMS/commit/9d1d4976339e4f9b08f096f7b0c2cfbed5b3f643
