### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by satish5577** [UMCUGenetics/DIMS#2]
I am a Phd student I am working with direct ms metabolomics , I want use this software to analyse my data, can you provide step by step user manual for DIMS?
I installed R studio

**Comment by poofcakes** [comment]
The DIMS pipeline in its current form is not compatible to simply run via RStudio. We run it on a high-performance computing server and it depends on the SGE job management system to be able to run a lot of jobs parallel. To be able to run is through RStudio, you would need someone who can read and adapt the code to your needs.

**Comment by satish5577** [comment]
Thanks, We have HPC too,  can you provide the steps to install it.

**Comment by poofcakes** [comment]
You really only need to clone the repo and then run the run.sh command as is described in the README. You will also need R version 3.2.2 with the libraries xcms, lattice and Cairo.
