### ISSUE TITLE
plots for single patients

### ISSUE THREAD

**Issue by FiniDG** [UMCUGenetics/DIMS#31]
make plots and excel for one specific patient or sample that has been analyzed multiple times over several RUNs. A script is already available, but not implemented fully yet. 
also think about how to arrange this in a structured way: 
1. Use one folder where to put data in --> run script before looking at data?
2. make a small database and update it with new information after every run

How the excel should look is already decided, but what about visualisations?

**Comment by FiniDG-HAN** [comment]
[OutputIndividuelePatient.docx](https://github.com/UMCUGenetics/DIMS/files/5266684/OutputIndividuelePatient.docx)

**Comment by FiniDG** [comment]
closed, because not really part of this pipeline, but a separate script about the results
