### ISSUE TITLE
can hmdb_part be universal?

### ISSUE THREAD

**Issue by FiniDG** [UMCUGenetics/DIMS#36]
script needs around 2 hours every time you run the script to run hmdb_part.R and splits the HMDB database in pieces and puts them in the output folder. By looking at the script itself it seems that the result does not vary much, depending on the ppm you select. Might it be possible to make a universal folder for each project to look into, and if settings are changed, calculate it like is done now?

investigate if the hmdb_part output is the same for different projects the script is run with the same settings.config

**Comment by mraves2** [comment]
This idea has been incorporated in DIMS version 2.3
